spring:
  application:
    name: springcloud-consumerfeign


eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

feign:
  hystrix:
    enabled: true


