spring:
  application:
    name: springcloud-eurekaconsumer-ribbon

server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

