spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-eurekaconsumer-ribbon


ribbon:
  ReadTimeout: 2600
  ConnectTimeout: 2600

